export const homeData = state => state.homeData
export const areaData = state => state.areaData
export const alertInfo = state => state.alertInfo
export const videoTims = state => state.videoTims
export const onlyOneItem = state => state.onlyOneItem
export const limitItem = state => state.limitItem
export const pageVisiable = state => state.pageVisiable
export const thirdUser = state => state.thirdUser
export const thirdConf = state => state.thirdConf
export const editId = state => state.editId